import Gimle.Forseti.Nonlinear
import Gimle.Forseti.GalerkinNS.Family
import Gimle.Asgard.Compile.Syntax

/-! # K5: a Galerkin truncation of 2D Navier–Stokes, trapped

Generated by tools/galerkin_ns.py; do not edit by hand. Every identity below
was checked by exact polynomial expansion before it was written, and is
checked again here by Lean.

Modes: a10 = (1, 0), a01 = (0, 1), a11 = (1, 1), a21 = (2, 1), a12 = (1, 2).
ν = 1/10, f = 1 on cos(x + y). Energy E = Σ a_k²/|k|²;
E' ≤ 2ν (f²/(8ν²) − E) = 1/5 · (25/2 − E), and the trapped level is
13 > 25/2, from the start (1, …, 1). Enstrophy Z = Σ a_k²;
Z' ≤ 2ν (f²/(4ν²) − Z) = 1/5 · (25 − Z), and the trapped level is
26 > 25. Unforced energy E_rest = Σ_{k ≠ (1,1)} a_k²/|k|²; the forced
mode's coupling sum is K = 4/5, so with r = 6 the rate
2ν − K r = -23/5 is not positive: no decay is claimed. -/

namespace Gimle.Forseti.Examples.GalerkinNS.K5

open Gimle.Forseti
open Gimle.Forseti.Trajectory
open Gimle.Asgard Gimle.Asgard.Model Gimle.Asgard.Polynomial

set_option maxRecDepth 4000
-- Generated tactic chains use `<;>` so that a `simp` closing a goal early is
-- not an error; the linters that flag that are off for this file.
set_option linter.unnecessarySeqFocus false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- The modes as states, the forced mode's equation carrying `f`, and the
energy, the enstrophy and the unforced energy as the last three observations. -/
def body : Body := {
  program := ⟨[⟨"state-a10", "a10", .state⟩, ⟨"state-a01", "a01", .state⟩, ⟨"state-a11", "a11", .state⟩, ⟨"state-a21", "a21", .state⟩, ⟨"state-a12", "a12", .state⟩],
    equations% {
      da10 := (-rat(1,10)) * a10 + (-rat(3,20)) * a11 * a21 + (-rat(1,4)) * a01 * a11;
      da01 := (-rat(1,10)) * a01 + rat(3,20) * a11 * a12 + rat(1,4) * a10 * a11;
      da11 := rat(1,1) + (-rat(1,5)) * a11 + (-rat(2,5)) * a01 * a12 + rat(2,5) * a10 * a21;
      da21 := (-rat(1,2)) * a21 + (-rat(1,4)) * a10 * a11;
      da12 := (-rat(1,2)) * a12 + rat(1,4) * a01 * a11;
      E := rat(1,1) * a10 * a10 + rat(1,1) * a01 * a01 + rat(1,2) * a11 * a11 + rat(1,5) * a21 * a21 + rat(1,5) * a12 * a12;
      Z := rat(1,1) * a10 * a10 + rat(1,1) * a01 * a01 + rat(1,1) * a11 * a11 + rat(1,1) * a21 * a21 + rat(1,1) * a12 * a12;
      R := rat(1,1) * a10 * a10 + rat(1,1) * a01 * a01 + rat(1,5) * a21 * a21 + rat(1,5) * a12 * a12;
    }⟩
  observations := [⟨⟨"obs-a10", "a10", .output⟩, "state-a10"⟩, ⟨⟨"obs-a01", "a01", .output⟩, "state-a01"⟩, ⟨⟨"obs-a11", "a11", .output⟩, "state-a11"⟩, ⟨⟨"obs-a21", "a21", .output⟩, "state-a21"⟩, ⟨⟨"obs-a12", "a12", .output⟩, "state-a12"⟩, ⟨⟨"obs-e", "E", .output⟩, "E"⟩, ⟨⟨"obs-z", "Z", .output⟩, "Z"⟩, ⟨⟨"obs-r", "R", .output⟩, "R"⟩]
}

/-- From `(1, …, 1)` at `t = 0`. -/
def evolution : Evolution := {
  states := [⟨"state-a10", "da10", "initial-a10"⟩, ⟨"state-a01", "da01", "initial-a01"⟩, ⟨"state-a11", "da11", "initial-a11"⟩, ⟨"state-a21", "da21", "initial-a21"⟩, ⟨"state-a12", "da12", "initial-a12"⟩]
  initialPorts := [⟨"initial-a10", "a10_0", .initial⟩, ⟨"initial-a01", "a01_0", .initial⟩, ⟨"initial-a11", "a11_0", .initial⟩, ⟨"initial-a21", "a21_0", .initial⟩, ⟨"initial-a12", "a12_0", .initial⟩]
  initialValues := [⟨"initial-a10", 1⟩, ⟨"initial-a01", 1⟩, ⟨"initial-a11", 1⟩, ⟨"initial-a21", 1⟩, ⟨"initial-a12", 1⟩]
  axis := ⟨"time", "t"⟩
  evolveAlong := "time"
  start := 0
}

def compiled : ContinuousModel body evolution :=
  (compileContinuous body evolution).toOption.get (by decide +kernel)

/-- The compiled right-hand sides, as the compiler normalises the source. -/
private theorem rates_expressions : compiled.rates.expressions =
    (![(.add (.add (.mul (.neg (.constant (1 / 10))) (.var 0)) (.mul (.mul (.neg (.constant (3 / 20))) (.var 2)) (.var 3))) (.mul (.mul (.neg (.constant (1 / 4))) (.var 1)) (.var 2))), (.add (.add (.mul (.neg (.constant (1 / 10))) (.var 1)) (.mul (.mul (.constant (3 / 20)) (.var 2)) (.var 4))) (.mul (.mul (.constant (1 / 4)) (.var 0)) (.var 2))), (.add (.add (.add (.constant (1 / 1)) (.mul (.neg (.constant (1 / 5))) (.var 2))) (.mul (.mul (.neg (.constant (2 / 5))) (.var 1)) (.var 4))) (.mul (.mul (.constant (2 / 5)) (.var 0)) (.var 3))), (.add (.mul (.neg (.constant (1 / 2))) (.var 3)) (.mul (.mul (.neg (.constant (1 / 4))) (.var 0)) (.var 2))), (.add (.mul (.neg (.constant (1 / 2))) (.var 4)) (.mul (.mul (.constant (1 / 4)) (.var 1)) (.var 2)))] : Fin 5 → Expr 5) := by decide +kernel

def energyIndex : Fin body.observations.length := ⟨5, by decide⟩

private theorem energy_expression : compiled.outputs.expressions energyIndex =
    ((.add (.add (.add (.add (.mul (.mul (.constant (1 / 1)) (.var 0)) (.var 0)) (.mul (.mul (.constant (1 / 1)) (.var 1)) (.var 1))) (.mul (.mul (.constant (1 / 2)) (.var 2)) (.var 2))) (.mul (.mul (.constant (1 / 5)) (.var 3)) (.var 3))) (.mul (.mul (.constant (1 / 5)) (.var 4)) (.var 4))) : Expr 5) := by decide +kernel

def enstrophyIndex : Fin body.observations.length := ⟨6, by decide⟩

private theorem enstrophy_expression : compiled.outputs.expressions enstrophyIndex =
    ((.add (.add (.add (.add (.mul (.mul (.constant (1 / 1)) (.var 0)) (.var 0)) (.mul (.mul (.constant (1 / 1)) (.var 1)) (.var 1))) (.mul (.mul (.constant (1 / 1)) (.var 2)) (.var 2))) (.mul (.mul (.constant (1 / 1)) (.var 3)) (.var 3))) (.mul (.mul (.constant (1 / 1)) (.var 4)) (.var 4))) : Expr 5) := by decide +kernel

def restIndex : Fin body.observations.length := ⟨7, by decide⟩

private theorem rest_expression : compiled.outputs.expressions restIndex =
    ((.add (.add (.add (.mul (.mul (.constant (1 / 1)) (.var 0)) (.var 0)) (.mul (.mul (.constant (1 / 1)) (.var 1)) (.var 1))) (.mul (.mul (.constant (1 / 5)) (.var 3)) (.var 3))) (.mul (.mul (.constant (1 / 5)) (.var 4)) (.var 4))) : Expr 5) := by decide +kernel

theorem initial_eq : compiled.initial = (![1, 1, 1, 1, 1] : Point 5) := by
  change (fun i : Fin 5 => (compiled.initials i : ℝ)) = _
  have values : compiled.initials = ![1, 1, 1, 1, 1] := by decide +kernel
  rw [values]
  ext i
  fin_cases i <;> norm_num

/-- The field in closed form, in state order. -/
noncomputable def field (x : Point 5) : Point 5 :=
  ![(-1 / 10 : ℝ) * x 0 + (-3 / 20 : ℝ) * x 2 * x 3 + (-1 / 4 : ℝ) * x 1 * x 2,
    (-1 / 10 : ℝ) * x 1 + (3 / 20 : ℝ) * x 2 * x 4 + (1 / 4 : ℝ) * x 0 * x 2,
    (1 / 1 : ℝ) + (-1 / 5 : ℝ) * x 2 + (-2 / 5 : ℝ) * x 1 * x 4 + (2 / 5 : ℝ) * x 0 * x 3,
    (-1 / 2 : ℝ) * x 3 + (-1 / 4 : ℝ) * x 0 * x 2,
    (-1 / 2 : ℝ) * x 4 + (1 / 4 : ℝ) * x 1 * x 2]

theorem rates_formula (x : Point 5) : compiled.rates.circuit.run x = field x := by
  rw [Selected.circuit, compileOutputs_correct, rates_expressions]
  ext i
  change Fin 5 at i
  fin_cases i <;> simp [field, Expr.eval] <;> ring

theorem rates_eval (i : Fin evolution.states.length) (x : Point evolution.states.length) :
    (compiled.rates.expressions i).eval x = field x i := by
  have h := congrFun (rates_formula x) i
  rwa [Selected.circuit, compileOutputs_correct] at h

theorem field_eq : Nonlinear.field compiled = field := by
  funext x i
  exact rates_eval i x

/-! ## The member as an instance of the family -/

/-- The modes as the family indexes them. -/
def modes : Fin 5 → GalerkinNS.Family.Wave :=
  ![(1, 0), (0, 1), (1, 1), (2, 1), (1, 2)]

/-- The index of the forced mode `(1, 1)`. -/
def forcedIndex : Fin 5 := 2

theorem modes_nonzero : ∀ i, modes i ≠ 0 := by decide

theorem modes_forced : modes forcedIndex = (1, 1) := by decide

private theorem coordinate_0 (x : Point 5) :
    field x 0 = GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex x 0 := by
  simp only [GalerkinNS.Family.field, Fin.sum_univ_succ, Fin.sum_univ_zero, modes,
    forcedIndex, field]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val] <;> ring

private theorem coordinate_1 (x : Point 5) :
    field x 1 = GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex x 1 := by
  simp only [GalerkinNS.Family.field, Fin.sum_univ_succ, Fin.sum_univ_zero, modes,
    forcedIndex, field]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val] <;> ring

private theorem coordinate_2 (x : Point 5) :
    field x 2 = GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex x 2 := by
  simp only [GalerkinNS.Family.field, Fin.sum_univ_succ, Fin.sum_univ_zero, modes,
    forcedIndex, field]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val] <;> ring

private theorem coordinate_3 (x : Point 5) :
    field x 3 = GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex x 3 := by
  simp only [GalerkinNS.Family.field, Fin.sum_univ_succ, Fin.sum_univ_zero, modes,
    forcedIndex, field]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val] <;> ring

private theorem coordinate_4 (x : Point 5) :
    field x 4 = GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex x 4 := by
  simp only [GalerkinNS.Family.field, Fin.sum_univ_succ, Fin.sum_univ_zero, modes,
    forcedIndex, field]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val] <;> ring

/-- The compiled field is the family field at these modes: the triad
coefficients are the ordered-pair coupling summed over both orders. -/
theorem field_eq_family :
    Nonlinear.field compiled =
      GalerkinNS.Family.field (1 / 10 : ℝ) (1 / 1 : ℝ) modes forcedIndex := by
  rw [field_eq]
  funext x i
  fin_cases i
  · exact coordinate_0 x
  · exact coordinate_1 x
  · exact coordinate_2 x
  · exact coordinate_3 x
  · exact coordinate_4 x

/-- `E = Σ a_k²/|k|²`. -/
noncomputable def energy (x : Point 5) : ℝ := x 0 * x 0 + x 1 * x 1 + (1 / 2 : ℝ) * x 2 * x 2 + (1 / 5 : ℝ) * x 3 * x 3 + (1 / 5 : ℝ) * x 4 * x 4

theorem energy_at (x : Point 5) :
    compiled.outputs.circuit.run x energyIndex = energy x := by
  rw [Selected.circuit, compileOutputs_correct]
  change (compiled.outputs.expressions energyIndex).eval x = _
  rw [energy_expression]
  simp [energy, Expr.eval] <;> ring

theorem energy_at_initial :
    compiled.outputs.circuit.run compiled.initial energyIndex = 29 / 10 := by
  rw [energy_at, initial_eq]
  simp [energy, Matrix.cons_val] <;> norm_num

theorem domain_iff (t : ℝ) : t ∈ evolution.time.domain ↔ 0 ≤ t := by
  simp [Dynamics.TimeDomain.domain, Evolution.time, evolution]

/-- `Z = Σ a_k²`. -/
noncomputable def enstrophy (x : Point 5) : ℝ := x 0 * x 0 + x 1 * x 1 + x 2 * x 2 + x 3 * x 3 + x 4 * x 4

theorem enstrophy_at (x : Point 5) :
    compiled.outputs.circuit.run x enstrophyIndex = enstrophy x := by
  rw [Selected.circuit, compileOutputs_correct]
  change (compiled.outputs.expressions enstrophyIndex).eval x = _
  rw [enstrophy_expression]
  simp [enstrophy, Expr.eval] <;> ring

theorem enstrophy_at_initial :
    compiled.outputs.circuit.run compiled.initial enstrophyIndex = 5 := by
  rw [enstrophy_at, initial_eq]
  simp [enstrophy, Matrix.cons_val] <;> norm_num

/-- `E_rest = Σ_{k ≠ (1,1)} a_k²/|k|²`, the unforced modes' energy. -/
noncomputable def rest (x : Point 5) : ℝ := x 0 * x 0 + x 1 * x 1 + (1 / 5 : ℝ) * x 3 * x 3 + (1 / 5 : ℝ) * x 4 * x 4

theorem rest_at (x : Point 5) :
    compiled.outputs.circuit.run x restIndex = rest x := by
  rw [Selected.circuit, compileOutputs_correct]
  change (compiled.outputs.expressions restIndex).eval x = _
  rw [rest_expression]
  simp [rest, Expr.eval] <;> ring

theorem rest_at_initial :
    compiled.outputs.circuit.run compiled.initial restIndex = 12 / 5 := by
  rw [rest_at, initial_eq]
  simp [rest, Matrix.cons_val] <;> norm_num

/-! ## The compositional identities: modes store, triads route -/

/-- Triad {a01, a10, a11}: its weighted energy flows sum to zero, and so
do its unweighted enstrophy flows; it is a lossless three-port. -/
theorem triad_0 :
    (1 / 1 : ℝ) * (1 / 4) + (1 / 1 : ℝ) * (-1 / 4) + (1 / 2 : ℝ) * (0 / 1) = 0 ∧
    (1 / 4 : ℝ) + (-1 / 4) + (0 / 1) = 0 := by
  norm_num

/-- Triad {a01, a11, a12}: its weighted energy flows sum to zero, and so
do its unweighted enstrophy flows; it is a lossless three-port. -/
theorem triad_1 :
    (1 / 1 : ℝ) * (3 / 20) + (1 / 2 : ℝ) * (-2 / 5) + (1 / 5 : ℝ) * (1 / 4) = 0 ∧
    (3 / 20 : ℝ) + (-2 / 5) + (1 / 4) = 0 := by
  norm_num

/-- Triad {a10, a11, a21}: its weighted energy flows sum to zero, and so
do its unweighted enstrophy flows; it is a lossless three-port. -/
theorem triad_2 :
    (1 / 1 : ℝ) * (-3 / 20) + (1 / 2 : ℝ) * (2 / 5) + (1 / 5 : ℝ) * (-1 / 4) = 0 ∧
    (-3 / 20 : ℝ) + (2 / 5) + (-1 / 4) = 0 := by
  norm_num

/-- Each mode's storage identity: dissipation, forcing, and one cubic term per
triad it belongs to. -/
theorem storage_a10 (x : Point 5) :
    2 * (1 / 1 : ℝ) * x 0 * field x 0 = (-1 / 5 : ℝ) * x 0 * x 0 + (-1 / 2 : ℝ) * x 0 * x 1 * x 2 + (-3 / 10 : ℝ) * x 0 * x 2 * x 3 := by
  simp [field] <;> ring

theorem storage_a01 (x : Point 5) :
    2 * (1 / 1 : ℝ) * x 1 * field x 1 = (-1 / 5 : ℝ) * x 1 * x 1 + (1 / 2 : ℝ) * x 0 * x 1 * x 2 + (3 / 10 : ℝ) * x 1 * x 2 * x 4 := by
  simp [field] <;> ring

theorem storage_a11 (x : Point 5) :
    2 * (1 / 2 : ℝ) * x 2 * field x 2 = (-1 / 5 : ℝ) * x 2 * x 2 + x 2 + (0 / 1 : ℝ) * x 0 * x 1 * x 2 + (-2 / 5 : ℝ) * x 1 * x 2 * x 4 + (2 / 5 : ℝ) * x 0 * x 2 * x 3 := by
  simp [field] <;> ring

theorem storage_a21 (x : Point 5) :
    2 * (1 / 5 : ℝ) * x 3 * field x 3 = (-1 / 5 : ℝ) * x 3 * x 3 + (-1 / 10 : ℝ) * x 0 * x 2 * x 3 := by
  simp [field] <;> ring

theorem storage_a12 (x : Point 5) :
    2 * (1 / 5 : ℝ) * x 4 * field x 4 = (-1 / 5 : ℝ) * x 4 * x 4 + (1 / 10 : ℝ) * x 1 * x 2 * x 4 := by
  simp [field] <;> ring

/-- The energy identity, the storage identities summed: the cubic terms cancel
triad by triad, leaving `E' = −2νZ + f a_(1,1)`. -/
theorem energy_identity (x : Point 5) :
    (∑ i, 2 * (![(1 / 1 : ℝ), (1 / 1 : ℝ), (1 / 2 : ℝ), (1 / 5 : ℝ), (1 / 5 : ℝ)] : Fin 5 → ℝ) i * x i * field x i) =
      -2 * (1 / 10 : ℝ) * (x 0 * x 0 + x 1 * x 1 + x 2 * x 2 + x 3 * x 3 + x 4 * x 4) + (1 / 1 : ℝ) * x 2 := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, field]
  simp [Matrix.cons_val] <;> ring

/-- The enstrophy identity: the same cancellation with the weights `1`, leaving
`Z' = −2ν Σ λ_k a_k² + 2 f a_(1,1)`. -/
theorem enstrophy_identity (x : Point 5) :
    (∑ i, 2 * x i * field x i) =
      -2 * (1 / 10 : ℝ) * (x 0 * x 0 + x 1 * x 1 + (2 / 1 : ℝ) * x 2 * x 2 + (5 / 1 : ℝ) * x 3 * x 3 + (5 / 1 : ℝ) * x 4 * x 4) + 2 * (1 / 1 : ℝ) * x 2 := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, field]
  simp [Matrix.cons_val] <;> ring

/-- **Only two diagonal invariants.** A weighting `w` for which every triad is
lossless — each hypothesis is one triad's `Σ w C = 0` — is a combination of
`1/λ` (energy) and `1` (enstrophy): there is no other diagonal quadratic the
triads conserve, so no reweighting of the modes traps tighter than these two. -/
theorem only_two_diagonal (w : Fin 5 → ℝ)
    (h0 : w 0 * (-1 / 4) + w 1 * (1 / 4) = 0)
    (h1 : w 1 * (3 / 20) + w 2 * (-2 / 5) + w 4 * (1 / 4) = 0)
    (h2 : w 0 * (-3 / 20) + w 2 * (2 / 5) + w 3 * (-1 / 4) = 0) :
    ∃ α β : ℝ, w 0 = α * (1 / 1) + β ∧
      w 1 = α * (1 / 1) + β ∧
      w 2 = α * (1 / 2) + β ∧
      w 3 = α * (1 / 5) + β ∧
      w 4 = α * (1 / 5) + β := by
  refine ⟨(w 0 - w 2) * (2 / 1), w 2 - (w 0 - w 2) * (2 / 1) / 2, ?_, ?_, ?_, ?_, ?_⟩
  · linear_combination
  · linear_combination (4 / 1 : ℝ) * h0
  · linear_combination
  · linear_combination (-4 / 1 : ℝ) * h2
  · linear_combination (-12 / 5 : ℝ) * h0 + (4 / 1 : ℝ) * h1

/-- A further conserved quadratic form, `(5 / 3 : ℝ) * x 0 * x 0 + (2 / 1 : ℝ) * x 0 * x 4 + (5 / 3 : ℝ) * x 1 * x 1 + (2 / 1 : ℝ) * x 1 * x 3`, beyond `E` and `Z`: its
flux along the field has no cubic part. It comes from a symmetry of the mode set
(a reflection exchanging modes), and no member without one has it. -/
theorem symmetric_invariant_0 (x : Point 5) :
    ((2 / 1 : ℝ) * x 4 + (10 / 3 : ℝ) * x 0) * field x 0 + ((2 / 1 : ℝ) * x 3 + (10 / 3 : ℝ) * x 1) * field x 1 + ((2 / 1 : ℝ) * x 1) * field x 3 + ((2 / 1 : ℝ) * x 0) * field x 4 = (-6 / 5 : ℝ) * x 1 * x 3 + (-1 / 3 : ℝ) * x 1 * x 1 + (-6 / 5 : ℝ) * x 0 * x 4 + (-1 / 3 : ℝ) * x 0 * x 0 := by
  simp [field] <;> ring

/-! ## The trapping data and the contract -/

/-- Weights `1/|k|²`, centre `0`, `α = 2ν`, inner level `f²/(8ν²)`, trapped level
`13`, sup-norm radius `9`. -/
noncomputable def trapping : Nonlinear.Trapping 5 where
  weights := ![1 / 1, 1 / 1, 1 / 2, 1 / 5, 1 / 5]
  centre := fun _ => 0
  alpha := 1 / 5
  inner := 25 / 2
  bound := 13
  radius := 9
  weights_pos := by intro i; fin_cases i <;> simp [Matrix.cons_val] <;> norm_num
  alpha_pos := by norm_num
  margin := by norm_num
  radius_nonneg := by norm_num
  covers := by intro i; fin_cases i <;> simp [Matrix.cons_val] <;> norm_num

theorem energy_eq_trapping (x : Point 5) : energy x = trapping.energy x := by
  simp [energy, trapping, Nonlinear.Trapping.energy, Fin.sum_univ_succ] <;> ring

/-- The certificate: `2ν (f²/(8ν²) − E) − E'` is a sum of squares with
nonnegative rational weights, `ν (a_(1,1) − f/(2ν))² + 2ν Σ (1 − 1/|k|²) a_k²`. -/
theorem certificate (x : Point 5) :
    trapping.alpha * (trapping.inner - trapping.energy x) - trapping.rate (Nonlinear.field compiled) x =
      (1 / 10 : ℝ) * (x 2 - 5 / 1) ^ 2 + (4 / 25 : ℝ) * x 3 ^ 2 + (4 / 25 : ℝ) * x 4 ^ 2 := by
  rw [field_eq]
  simp only [trapping, Nonlinear.Trapping.rate, Nonlinear.Trapping.energy, field, Fin.sum_univ_succ, Fin.sum_univ_zero]
  simp [Matrix.cons_val] <;> ring

theorem decrease (x : Point 5) :
    trapping.rate (Nonlinear.field compiled) x ≤ trapping.alpha * (trapping.inner - trapping.energy x) := by
  have h := certificate x
  have nonneg : 0 ≤ (1 / 10 : ℝ) * (x 2 - 5 / 1) ^ 2 + (4 / 25 : ℝ) * x 3 ^ 2 + (4 / 25 : ℝ) * x 4 ^ 2 := by positivity
  linarith

theorem rate_eq_family (F : Point 5 → Point 5) (x : Point 5) :
    trapping.rate F x = GalerkinNS.Family.rate modes F x := by
  unfold Nonlinear.Trapping.rate GalerkinNS.Family.rate
  refine Finset.sum_congr rfl fun i _ => ?_
  fin_cases i <;> simp [trapping, modes, GalerkinNS.Family.lam, Matrix.cons_val,
    -mul_eq_mul_right_iff, -mul_eq_mul_left_iff] <;> ring

theorem energy_eq_family (x : Point 5) :
    trapping.energy x = GalerkinNS.Family.energy modes x := by
  unfold Nonlinear.Trapping.energy GalerkinNS.Family.energy
  refine Finset.sum_congr rfl fun i _ => ?_
  fin_cases i <;> simp [trapping, modes, GalerkinNS.Family.lam, Matrix.cons_val,
    -mul_eq_mul_right_iff, -mul_eq_mul_left_iff] <;> ring

/-- `decrease` again, by the family theorem through `field_eq_family`: a second
route to the same inequality over the same `field_eq` and `trapping`, with the
identity by `Family.decrease_rate` instead of `ring`. -/
theorem decrease_family (x : Point 5) :
    trapping.rate (Nonlinear.field compiled) x ≤
      trapping.alpha * (trapping.inner - trapping.energy x) := by
  rw [rate_eq_family, energy_eq_family, field_eq_family]
  have alpha_eq : trapping.alpha = 2 * (1 / 10 : ℝ) := by norm_num [trapping]
  have inner_eq : trapping.inner = (1 / 1 : ℝ) ^ 2 / (8 * (1 / 10 : ℝ) ^ 2) := by
    norm_num [trapping]
  rw [alpha_eq, inner_eq]
  exact GalerkinNS.Family.decrease_rate (1 / 10 : ℝ) (1 / 1 : ℝ) (by norm_num) modes modes_nonzero
    forcedIndex modes_forced x

theorem initial_le : trapping.energy compiled.initial ≤ trapping.bound := by
  rw [← energy_eq_trapping, initial_eq]
  simp [energy, trapping, Matrix.cons_val] <;> norm_num

/-! ## The enstrophy ball -/

/-- Weights `1`, centre `0`, `α = 2ν`, inner level `f²/(4ν²)`, trapped level
`26`, sup-norm radius `6`. -/
noncomputable def trappingZ : Nonlinear.Trapping 5 where
  weights := fun _ => 1
  centre := fun _ => 0
  alpha := 1 / 5
  inner := 25 / 1
  bound := 26
  radius := 6
  weights_pos := fun _ => one_pos
  alpha_pos := by norm_num
  margin := by norm_num
  radius_nonneg := by norm_num
  covers := fun _ => by norm_num

theorem enstrophy_eq_trappingZ (x : Point 5) : enstrophy x = trappingZ.energy x := by
  simp [enstrophy, trappingZ, Nonlinear.Trapping.energy, Fin.sum_univ_succ] <;> ring

/-- The enstrophy certificate: `2ν (f²/(4ν²) − Z) − Z'` is a sum of squares,
`2ν (a_(1,1) − f/(2ν))² + 2ν Σ (|k|² − 1) a_k²`. -/
theorem certificateZ (x : Point 5) :
    trappingZ.alpha * (trappingZ.inner - trappingZ.energy x) - trappingZ.rate (Nonlinear.field compiled) x =
      (2 * (1 / 10) : ℝ) * (x 2 - 5 / 1) ^ 2 + (4 / 5 : ℝ) * x 3 ^ 2 + (4 / 5 : ℝ) * x 4 ^ 2 := by
  rw [field_eq]
  simp only [trappingZ, Nonlinear.Trapping.rate, Nonlinear.Trapping.energy, field, Fin.sum_univ_succ, Fin.sum_univ_zero]
  simp [Matrix.cons_val] <;> ring

theorem decreaseZ (x : Point 5) :
    trappingZ.rate (Nonlinear.field compiled) x ≤ trappingZ.alpha * (trappingZ.inner - trappingZ.energy x) := by
  have h := certificateZ x
  have nonneg : 0 ≤ (2 * (1 / 10) : ℝ) * (x 2 - 5 / 1) ^ 2 + (4 / 5 : ℝ) * x 3 ^ 2 + (4 / 5 : ℝ) * x 4 ^ 2 := by positivity
  linarith

theorem rateZ_eq_family (F : Point 5 → Point 5) (x : Point 5) :
    trappingZ.rate F x = GalerkinNS.Family.zrate F x := by
  unfold Nonlinear.Trapping.rate GalerkinNS.Family.zrate
  refine Finset.sum_congr rfl fun i _ => ?_
  simp [trappingZ]

theorem enstrophy_eq_family (x : Point 5) :
    trappingZ.energy x = GalerkinNS.Family.enstrophy x := by
  unfold Nonlinear.Trapping.energy GalerkinNS.Family.enstrophy
  refine Finset.sum_congr rfl fun i _ => ?_
  simp [trappingZ]

/-- `decreaseZ` again, by the family theorem through `field_eq_family`. -/
theorem decreaseZ_family (x : Point 5) :
    trappingZ.rate (Nonlinear.field compiled) x ≤
      trappingZ.alpha * (trappingZ.inner - trappingZ.energy x) := by
  rw [rateZ_eq_family, enstrophy_eq_family, field_eq_family]
  have alpha_eq : trappingZ.alpha = 2 * (1 / 10 : ℝ) := by norm_num [trappingZ]
  have inner_eq : trappingZ.inner = (1 / 1 : ℝ) ^ 2 / (4 * (1 / 10 : ℝ) ^ 2) := by
    norm_num [trappingZ]
  rw [alpha_eq, inner_eq]
  exact GalerkinNS.Family.enstrophy_decrease_rate (1 / 10 : ℝ) (1 / 1 : ℝ) (by norm_num) modes modes_nonzero
    forcedIndex modes_forced x

theorem initial_leZ : trappingZ.energy compiled.initial ≤ trappingZ.bound := by
  rw [← enstrophy_eq_trappingZ, initial_eq]
  simp [enstrophy, trappingZ, Matrix.cons_val] <;> norm_num

/-! ## The unforced energy -/

theorem rest_eq_family (x : Point 5) :
    rest x = GalerkinNS.Family.restEnergy modes forcedIndex x := by
  unfold rest GalerkinNS.Family.restEnergy GalerkinNS.Family.energy
  simp [modes, forcedIndex, GalerkinNS.Family.lam, Fin.sum_univ_succ] <;> ring

/-- `K = Σ_{j,l} |(c(k_j, k_l, (1,1)) + c(k_l, k_j, (1,1)))/2| = 4/5`, the forced mode's coupling sum. -/
theorem couplingSum_eq :
    GalerkinNS.Family.couplingSum modes forcedIndex = 4 / 5 := by
  simp only [GalerkinNS.Family.couplingSum, GalerkinNS.Family.symCoefficient, Fin.sum_univ_succ, Fin.sum_univ_zero, modes, forcedIndex]
  simp [GalerkinNS.Family.coefficient, GalerkinNS.Family.S, GalerkinNS.Family.cross,
    GalerkinNS.Family.lam, Matrix.cons_val]
  norm_num

/-! ## The interface gimle-forseti's trajectory registry cites -/

def observed := LinearEnergyContract.observed compiled

def admitted : Trajectory.SignalPredicate (0 + evolution.states.length) :=
  LinearEnergyContract.admitted compiled

theorem feedback_reads (input : Dynamics.Signal (0 + evolution.states.length))
    (admit : admitted input) (state : Dynamics.Signal evolution.states.length) :
    compiled.feedback.Rel evolution.time input state ↔ compiled.Realizes state :=
  LinearEnergyContract.feedback_reads compiled input admit state

theorem declared_input_admitted :
    admitted (Dynamics.signalAppend Model.noDrivers fun _ => compiled.initial) :=
  LinearEnergyContract.declared_input_admitted compiled

theorem compiled_exists : ∃ state, compiled.Realizes state :=
  Nonlinear.compiled_exists compiled trapping decrease initial_le

theorem compiled_unique {x y : Dynamics.Signal 5}
    (hx : compiled.Realizes x) (hy : compiled.Realizes y) :
    Set.EqOn x y evolution.time.domain :=
  Nonlinear.compiled_unique compiled trapping decrease initial_le hx hy

theorem energy_at_trapping (x : Point 5) :
    compiled.outputs.circuit.run x energyIndex = trapping.energy x := by
  rw [energy_at, energy_eq_trapping]

/-- **The trajectory stays in the ball `E ≤ 13`**, for every admitted input. -/
theorem energy_contract :
    Contract observed evolution.time admitted
      (Always evolution.time fun observation =>
        0 ≤ observation energyIndex ∧ observation energyIndex ≤ 13) :=
  Nonlinear.energy_contract compiled trapping energyIndex energy_at_trapping decrease initial_le

theorem enstrophy_at_trappingZ (x : Point 5) :
    compiled.outputs.circuit.run x enstrophyIndex = trappingZ.energy x := by
  rw [enstrophy_at, enstrophy_eq_trappingZ]

/-- **The trajectory stays in the enstrophy ball `Z ≤ 26`**, for every
admitted input; the level `f²/(4ν²)` is the same for every member of the family. -/
theorem enstrophy_contract :
    Contract observed evolution.time admitted
      (Always evolution.time fun observation =>
        0 ≤ observation enstrophyIndex ∧ observation enstrophyIndex ≤ 26) :=
  Nonlinear.energy_contract compiled trappingZ enstrophyIndex enstrophy_at_trappingZ decreaseZ initial_leZ

/-- `1` is not a bound: `E = 29/10` at the start. -/
theorem refuted :
    ¬ Holds observed evolution.time admitted
      (Always evolution.time fun observation => observation energyIndex ≤ 1) :=
  Nonlinear.refuted compiled trapping energyIndex energy_at_trapping decrease initial_le 1
    (by
      show (1 : ℝ) < @Nonlinear.Trapping.energy 5 trapping compiled.initial
      rw [← energy_eq_trapping, initial_eq]
      simp [energy, Matrix.cons_val] <;> norm_num)

#print axioms energy_identity
#print axioms certificate
#print axioms field_eq_family
#print axioms decrease_family
#print axioms energy_contract
#print axioms refuted
#print axioms enstrophy_identity
#print axioms only_two_diagonal
#print axioms enstrophy_contract
#print axioms couplingSum_eq

end Gimle.Forseti.Examples.GalerkinNS.K5
