import Gimle.Forseti.Nonlinear
import Gimle.Asgard.Compile.Syntax

/-! # T3: a Galerkin truncation of 2D Navier–Stokes, trapped

Generated by tools/galerkin_ns.py; do not edit by hand. Every identity below
was checked by exact polynomial expansion before it was written, and is
checked again here by Lean.

Modes: a10 = (1, 0), a11 = (1, 1), a21 = (2, 1).
ν = 1/10, f = 1 on cos(x + y). Energy E = Σ a_k²/|k|²;
E' ≤ 2ν (f²/(8ν²) − E) = 1/5 · (25/2 − E), and the trapped level is
13 > 25/2, from the start (1, …, 1). -/

namespace Gimle.Forseti.Examples.GalerkinNS.T3

open Gimle.Forseti
open Gimle.Forseti.Trajectory
open Gimle.Asgard Gimle.Asgard.Model Gimle.Asgard.Polynomial

set_option maxRecDepth 4000
-- Generated tactic chains use `<;>` so that a `simp` closing a goal early is
-- not an error; the linters that flag that are off for this file.
set_option linter.unnecessarySeqFocus false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- The modes as states, the forced mode's equation carrying `f`, and the
energy as the last observation. -/
def body : Body := {
  program := ⟨[⟨"state-a10", "a10", .state⟩, ⟨"state-a11", "a11", .state⟩, ⟨"state-a21", "a21", .state⟩],
    equations% {
      da10 := (-rat(1,10)) * a10 + (-rat(3,20)) * a11 * a21;
      da11 := rat(1,1) + (-rat(1,5)) * a11 + rat(2,5) * a10 * a21;
      da21 := (-rat(1,2)) * a21 + (-rat(1,4)) * a10 * a11;
      E := rat(1,1) * a10 * a10 + rat(1,2) * a11 * a11 + rat(1,5) * a21 * a21;
    }⟩
  observations := [⟨⟨"obs-a10", "a10", .output⟩, "state-a10"⟩, ⟨⟨"obs-a11", "a11", .output⟩, "state-a11"⟩, ⟨⟨"obs-a21", "a21", .output⟩, "state-a21"⟩, ⟨⟨"obs-e", "E", .output⟩, "E"⟩]
}

/-- From `(1, …, 1)` at `t = 0`. -/
def evolution : Evolution := {
  states := [⟨"state-a10", "da10", "initial-a10"⟩, ⟨"state-a11", "da11", "initial-a11"⟩, ⟨"state-a21", "da21", "initial-a21"⟩]
  initialPorts := [⟨"initial-a10", "a10_0", .initial⟩, ⟨"initial-a11", "a11_0", .initial⟩, ⟨"initial-a21", "a21_0", .initial⟩]
  initialValues := [⟨"initial-a10", 1⟩, ⟨"initial-a11", 1⟩, ⟨"initial-a21", 1⟩]
  axis := ⟨"time", "t"⟩
  evolveAlong := "time"
  start := 0
}

def compiled : ContinuousModel body evolution :=
  (compileContinuous body evolution).toOption.get (by decide +kernel)

/-- The compiled right-hand sides, as the compiler normalises the source. -/
private theorem rates_expressions : compiled.rates.expressions =
    (![(.add (.mul (.neg (.constant (1 / 10))) (.var 0)) (.mul (.mul (.neg (.constant (3 / 20))) (.var 1)) (.var 2))), (.add (.add (.constant (1 / 1)) (.mul (.neg (.constant (1 / 5))) (.var 1))) (.mul (.mul (.constant (2 / 5)) (.var 0)) (.var 2))), (.add (.mul (.neg (.constant (1 / 2))) (.var 2)) (.mul (.mul (.neg (.constant (1 / 4))) (.var 0)) (.var 1)))] : Fin 3 → Expr 3) := by decide +kernel

def energyIndex : Fin body.observations.length := ⟨3, by decide⟩

private theorem energy_expression : compiled.outputs.expressions energyIndex =
    ((.add (.add (.mul (.mul (.constant (1 / 1)) (.var 0)) (.var 0)) (.mul (.mul (.constant (1 / 2)) (.var 1)) (.var 1))) (.mul (.mul (.constant (1 / 5)) (.var 2)) (.var 2))) : Expr 3) := by decide +kernel

theorem initial_eq : compiled.initial = (![1, 1, 1] : Point 3) := by
  change (fun i : Fin 3 => (compiled.initials i : ℝ)) = _
  have values : compiled.initials = ![1, 1, 1] := by decide +kernel
  rw [values]
  ext i
  fin_cases i <;> norm_num

/-- The field in closed form, in state order. -/
noncomputable def field (x : Point 3) : Point 3 :=
  ![(-1 / 10 : ℝ) * x 0 + (-3 / 20 : ℝ) * x 1 * x 2,
    (1 / 1 : ℝ) + (-1 / 5 : ℝ) * x 1 + (2 / 5 : ℝ) * x 0 * x 2,
    (-1 / 2 : ℝ) * x 2 + (-1 / 4 : ℝ) * x 0 * x 1]

theorem rates_formula (x : Point 3) : compiled.rates.circuit.run x = field x := by
  rw [Selected.circuit, compileOutputs_correct, rates_expressions]
  ext i
  change Fin 3 at i
  fin_cases i <;> simp [field, Expr.eval] <;> ring

theorem rates_eval (i : Fin evolution.states.length) (x : Point evolution.states.length) :
    (compiled.rates.expressions i).eval x = field x i := by
  have h := congrFun (rates_formula x) i
  rwa [Selected.circuit, compileOutputs_correct] at h

theorem field_eq : Nonlinear.field compiled = field := by
  funext x i
  exact rates_eval i x

/-- `E = Σ a_k²/|k|²`. -/
noncomputable def energy (x : Point 3) : ℝ := x 0 * x 0 + (1 / 2 : ℝ) * x 1 * x 1 + (1 / 5 : ℝ) * x 2 * x 2

theorem energy_at (x : Point 3) :
    compiled.outputs.circuit.run x energyIndex = energy x := by
  rw [Selected.circuit, compileOutputs_correct]
  change (compiled.outputs.expressions energyIndex).eval x = _
  rw [energy_expression]
  simp [energy, Expr.eval] <;> ring

theorem energy_at_initial :
    compiled.outputs.circuit.run compiled.initial energyIndex = 17 / 10 := by
  rw [energy_at, initial_eq]
  simp [energy, Matrix.cons_val] <;> norm_num

theorem domain_iff (t : ℝ) : t ∈ evolution.time.domain ↔ 0 ≤ t := by
  simp [Dynamics.TimeDomain.domain, Evolution.time, evolution]

/-! ## The compositional identities: modes store, triads route -/

/-- Triad {a10, a11, a21}: its weighted energy flows sum to zero, and so
do its unweighted enstrophy flows; it is a lossless three-port. -/
theorem triad_0 :
    (1 / 1 : ℝ) * (-3 / 20) + (1 / 2 : ℝ) * (2 / 5) + (1 / 5 : ℝ) * (-1 / 4) = 0 ∧
    (-3 / 20 : ℝ) + (2 / 5) + (-1 / 4) = 0 := by
  norm_num

/-- Each mode's storage identity: dissipation, forcing, and one cubic term per
triad it belongs to. -/
theorem storage_a10 (x : Point 3) :
    2 * (1 / 1 : ℝ) * x 0 * field x 0 = (-1 / 5 : ℝ) * x 0 * x 0 + (-3 / 10 : ℝ) * x 0 * x 1 * x 2 := by
  simp [field] <;> ring

theorem storage_a11 (x : Point 3) :
    2 * (1 / 2 : ℝ) * x 1 * field x 1 = (-1 / 5 : ℝ) * x 1 * x 1 + x 1 + (2 / 5 : ℝ) * x 0 * x 1 * x 2 := by
  simp [field] <;> ring

theorem storage_a21 (x : Point 3) :
    2 * (1 / 5 : ℝ) * x 2 * field x 2 = (-1 / 5 : ℝ) * x 2 * x 2 + (-1 / 10 : ℝ) * x 0 * x 1 * x 2 := by
  simp [field] <;> ring

/-- The energy identity, the storage identities summed: the cubic terms cancel
triad by triad, leaving `E' = −2νZ + f a_(1,1)`. -/
theorem energy_identity (x : Point 3) :
    (∑ i, 2 * (![(1 / 1 : ℝ), (1 / 2 : ℝ), (1 / 5 : ℝ)] : Fin 3 → ℝ) i * x i * field x i) =
      -2 * (1 / 10 : ℝ) * (x 0 * x 0 + x 1 * x 1 + x 2 * x 2) + (1 / 1 : ℝ) * x 1 := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, field]
  simp [Matrix.cons_val] <;> ring

/-! ## The trapping data and the contract -/

/-- Weights `1/|k|²`, centre `0`, `α = 2ν`, inner level `f²/(8ν²)`, trapped level
`13`, sup-norm radius `9`. -/
noncomputable def trapping : Nonlinear.Trapping 3 where
  weights := ![1 / 1, 1 / 2, 1 / 5]
  centre := fun _ => 0
  alpha := 1 / 5
  inner := 25 / 2
  bound := 13
  radius := 9
  weights_pos := by intro i; fin_cases i <;> simp [Matrix.cons_val] <;> norm_num
  alpha_pos := by norm_num
  margin := by norm_num
  radius_nonneg := by norm_num
  covers := by intro i; fin_cases i <;> simp [Matrix.cons_val] <;> norm_num

theorem energy_eq_trapping (x : Point 3) : energy x = trapping.energy x := by
  simp [energy, trapping, Nonlinear.Trapping.energy, Fin.sum_univ_succ] <;> ring

/-- The certificate: `2ν (f²/(8ν²) − E) − E'` is a sum of squares with
nonnegative rational weights, `ν (a_(1,1) − f/(2ν))² + 2ν Σ (1 − 1/|k|²) a_k²`. -/
theorem certificate (x : Point 3) :
    trapping.alpha * (trapping.inner - trapping.energy x) - trapping.rate (Nonlinear.field compiled) x =
      (1 / 10 : ℝ) * (x 1 - 5 / 1) ^ 2 + (4 / 25 : ℝ) * x 2 ^ 2 := by
  rw [field_eq]
  simp only [trapping, Nonlinear.Trapping.rate, Nonlinear.Trapping.energy, field, Fin.sum_univ_succ, Fin.sum_univ_zero]
  simp [Matrix.cons_val] <;> ring

theorem decrease (x : Point 3) :
    trapping.rate (Nonlinear.field compiled) x ≤ trapping.alpha * (trapping.inner - trapping.energy x) := by
  have h := certificate x
  have nonneg : 0 ≤ (1 / 10 : ℝ) * (x 1 - 5 / 1) ^ 2 + (4 / 25 : ℝ) * x 2 ^ 2 := by positivity
  linarith

theorem initial_le : trapping.energy compiled.initial ≤ trapping.bound := by
  rw [← energy_eq_trapping, initial_eq]
  simp [energy, trapping, Matrix.cons_val] <;> norm_num

/-! ## The interface gimle-forseti's trajectory registry cites -/

def observed := LinearEnergyContract.observed compiled

def admitted : Trajectory.SignalPredicate (0 + evolution.states.length) :=
  LinearEnergyContract.admitted compiled

theorem feedback_reads (input : Dynamics.Signal (0 + evolution.states.length))
    (admit : admitted input) (state : Dynamics.Signal evolution.states.length) :
    compiled.feedback.Rel evolution.time input state ↔ compiled.Realizes state :=
  LinearEnergyContract.feedback_reads compiled input admit state

theorem declared_input_admitted :
    admitted (Dynamics.signalAppend Model.noDrivers fun _ => compiled.initial) :=
  LinearEnergyContract.declared_input_admitted compiled

theorem compiled_exists : ∃ state, compiled.Realizes state :=
  Nonlinear.compiled_exists compiled trapping decrease initial_le

theorem compiled_unique {x y : Dynamics.Signal 3}
    (hx : compiled.Realizes x) (hy : compiled.Realizes y) :
    Set.EqOn x y evolution.time.domain :=
  Nonlinear.compiled_unique compiled trapping decrease initial_le hx hy

theorem energy_at_trapping (x : Point 3) :
    compiled.outputs.circuit.run x energyIndex = trapping.energy x := by
  rw [energy_at, energy_eq_trapping]

/-- **The trajectory stays in the ball `E ≤ 13`**, for every admitted input. -/
theorem energy_contract :
    Contract observed evolution.time admitted
      (Always evolution.time fun observation =>
        0 ≤ observation energyIndex ∧ observation energyIndex ≤ 13) :=
  Nonlinear.energy_contract compiled trapping energyIndex energy_at_trapping decrease initial_le

/-- `1` is not a bound: `E = 17/10` at the start. -/
theorem refuted :
    ¬ Holds observed evolution.time admitted
      (Always evolution.time fun observation => observation energyIndex ≤ 1) :=
  Nonlinear.refuted compiled trapping energyIndex energy_at_trapping decrease initial_le 1
    (by
      show (1 : ℝ) < @Nonlinear.Trapping.energy 3 trapping compiled.initial
      rw [← energy_eq_trapping, initial_eq]
      simp [energy, Matrix.cons_val] <;> norm_num)

#print axioms energy_identity
#print axioms certificate
#print axioms energy_contract
#print axioms refuted

end Gimle.Forseti.Examples.GalerkinNS.T3
