#!/usr/bin/env python3
"""Emit an untrusted exact AIF metric certificate; Lean checks the proposal.

Input is the hash-bound candidate from gimle-forseti PR #235. Neither SciPy,
floating point, nor Python success is used as proof authority.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from fractions import Fraction as F
from math import comb
from pathlib import Path

from search_suspension import ldl

CANDIDATE_SHA256 = (
    "96c882a6183ef5cd7e42e517092e50d0a78358a378dd94390241ffa4b92f2c39"
)
DESTINATION = (
    Path(__file__).resolve().parents[1]
    / "Gimle/Forseti/Examples/AIFMetricPilot.lean"
)


def rat(value: F) -> str:
    """Render a rational literal with explicit parentheses."""
    return f"({value.numerator} / {value.denominator})"


def vector(values: list[F]) -> str:
    """Render a finite rational vector."""
    return "![" + ", ".join(map(rat, values)) + "]"


def matrix(values: list[list[F]]) -> str:
    """Render a finite rational matrix."""
    return "![" + ",\n    ".join(map(vector, values)) + "]"


def generate(path: Path) -> str:
    """Propose four square certificates for bin zero, t in [33/5,67/10]."""
    payload = path.read_bytes()
    if hashlib.sha256(payload).hexdigest() != CANDIDATE_SHA256:
        raise ValueError("candidate SHA-256 mismatch")
    data = json.loads(gzip.decompress(payload))
    times = list(map(F, data["time_nodes"]))
    index = times.index(F(33, 5))
    if times[index + 1] != F(67, 10):
        raise ValueError("unexpected pilot time interval")
    denominator = data["denominator"]
    raw = data["tubes"][0]
    endpoints = [
        [[F(v, denominator) for v in row] for row in raw[k][i]]
        for k, i in [(4, index), (4, index + 1), (5, index), (5, index + 1)]
    ]
    p0, p1, d0, d1 = endpoints
    h = F(1, 10)
    power = [
        p0,
        [[h * d0[i][j] for j in range(4)] for i in range(4)],
        [
            [
                3 * (p1[i][j] - p0[i][j]) - h * (2 * d0[i][j] + d1[i][j])
                for j in range(4)
            ]
            for i in range(4)
        ],
        [
            [
                2 * (p0[i][j] - p1[i][j]) + h * (d0[i][j] + d1[i][j])
                for j in range(4)
            ]
            for i in range(4)
        ],
    ]
    a, b, c, d = power
    a = [[a[i][j] - F(i == j, 50) for j in range(4)] for i in range(4)]
    bernstein = [
        [
            [
                sum(
                    F(comb(k, ell), comb(3, ell)) * [a, b, c, d][ell][i][j]
                    for ell in range(k + 1)
                )
                for j in range(4)
            ]
            for i in range(4)
        ]
        for k in range(4)
    ]
    source = (
        """import Gimle.Forseti.BernsteinMatrix

/-! Generated by `tools/aif_metric_pilot.py`.
Untrusted proposals checked by the kernel.
Candidate gzip SHA-256: """
        + CANDIDATE_SHA256
        + """.
Bin eta ∈ [8,17/2], physical t ∈ [33/5,67/10], s = 10*(t-33/5).
This proves only metric coercivity, not drift, coverage or any trajectory. -/
namespace Gimle.Forseti.Examples.AIFMetricPilot
open Gimle.Forseti.LinearEnergy Gimle.Forseti.BernsteinMatrix

"""
    )
    for name, values in zip(
        ["startMetric", "endMetric", "startSlope", "endSlope"],
        endpoints,
        strict=True,
    ):
        source += f"def {name} : QMatrix 4 :=\n  {matrix(values)}\n\n"
    source += """-- Recompute the target from the rational Hermite inputs.
def linear : QMatrix 4 := scale (1/10) startSlope
def quadraticTerm : QMatrix 4 := fun i j =>
  3 * (endMetric i j - startMetric i j) -
    (1/10) * (2 * startSlope i j + endSlope i j)
def cubicTerm : QMatrix 4 := fun i j =>
  2 * (startMetric i j - endMetric i j) +
    (1/10) * (startSlope i j + endSlope i j)
def margin : QMatrix 4 :=
  fun i j => startMetric i j - if i = j then 1/50 else 0

"""
    for k, coeff in enumerate(bernstein):
        weights, vectors = ldl(coeff)
        source += f"""def certificate{k} : WeightedSquares 4 where
  count := 4
  weight := {vector(weights)}
  vector := {matrix(vectors)}

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem valid{k} : certificate{k}.Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm {k} 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

"""
    source += """def certificates : Fin 4 → Fin 1 → WeightedSquares 4 :=
  fun i _ => ![certificate0, certificate1, certificate2, certificate3] i

theorem valid : ∀ i j, (certificates i j).Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm i j) := by
  intro i j
  fin_cases i <;> fin_cases j
  · exact valid0
  · exact valid1
  · exact valid2
  · exact valid3

/-- A whole-interval inequality retaining the original Hermite inputs. -/
theorem margin_nonnegative (s : ℝ) (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (x : Fin 4 → ℝ) :
    0 ≤ cubicQuadratic margin linear quadraticTerm cubicTerm s x := by
  rw [← cubic_identity (u := 0)]
  exact tensor_nonnegative certificates valid hs (by norm_num) x

/-- The actual cubic metric controls all four real error coordinates. -/
theorem coercive (s : ℝ) (hs : s ∈ Set.Icc (0 : ℝ) 1) (x : Fin 4 → ℝ) :
    (∑ i, (x i)^2) / 50 ≤
      cubicQuadratic startMetric linear quadraticTerm cubicTerm s x := by
  have h := margin_nonnegative s hs x
  have eq : quadratic margin x =
      quadratic startMetric x - (∑ i, (x i)^2) / 50 := by
    simp [quadratic, realMatrix, margin, Matrix.mulVec, dotProduct,
      Fin.sum_univ_succ]
    ring
  simp only [cubicQuadratic, eq] at h ⊢
  linarith

/-- The same inequality on the candidate's declared physical time interval. -/
theorem coercive_time (t : ℝ) (ht : t ∈ Set.Icc (33/5 : ℝ) (67/10))
    (x : Fin 4 → ℝ) :
    (∑ i, (x i)^2) / 50 ≤ cubicQuadratic startMetric linear quadraticTerm
      cubicTerm (10 * (t - 33/5)) x := by
  apply coercive _ _ x
  constructor <;> linarith [ht.1, ht.2]

#print axioms coercive_time
#print axioms margin_nonnegative
#print axioms coercive
end Gimle.Forseti.Examples.AIFMetricPilot
"""
    return source


def main() -> None:
    """Generate the fixed pilot or verify byte-for-byte reproduction."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidate", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generate(args.candidate)
    if args.check:
        if DESTINATION.read_text() != source:
            raise SystemExit("generated pilot differs")
    else:
        DESTINATION.write_text(source)


if __name__ == "__main__":
    main()
