import Gimle.Forseti.Examples.GalerkinNS.T3
import Gimle.Forseti.Examples.GalerkinNS.K5
import Gimle.Forseti.Examples.GalerkinNS.B2

/-! Coverage for the Galerkin members' trajectory contracts.

gimle-forseti's trajectory registry cites these constants by name for each
member; each `example` restates one with its exact statement so a change fails
here rather than in a replay. The axiom policy is asserted with `#guard_msgs`.
The members are generated by `tools/galerkin_ns.py`, so the names are the
same in every member; T3 is pinned in full and the others by their contracts.
-/

namespace Gimle.Forseti.Tests.GalerkinNS

open Gimle.Forseti.Trajectory
open Gimle.Asgard

/-! ### T3, in full -/

example : Model.Body := Gimle.Forseti.Examples.GalerkinNS.T3.body
example : Model.Evolution := Gimle.Forseti.Examples.GalerkinNS.T3.evolution
example : Model.ContinuousModel Gimle.Forseti.Examples.GalerkinNS.T3.body
    Gimle.Forseti.Examples.GalerkinNS.T3.evolution :=
  Gimle.Forseti.Examples.GalerkinNS.T3.compiled
example : Fin Gimle.Forseti.Examples.GalerkinNS.T3.body.observations.length :=
  Gimle.Forseti.Examples.GalerkinNS.T3.energyIndex
example : Gimle.Forseti.Examples.GalerkinNS.T3.compiled.initial = ![1, 1, 1] :=
  Gimle.Forseti.Examples.GalerkinNS.T3.initial_eq
example : Gimle.Forseti.Examples.GalerkinNS.T3.compiled.outputs.circuit.run
    Gimle.Forseti.Examples.GalerkinNS.T3.compiled.initial
    Gimle.Forseti.Examples.GalerkinNS.T3.energyIndex = 17 / 10 :=
  Gimle.Forseti.Examples.GalerkinNS.T3.energy_at_initial
example : Fin Gimle.Forseti.Examples.GalerkinNS.T3.body.observations.length :=
  Gimle.Forseti.Examples.GalerkinNS.T3.enstrophyIndex
example : Gimle.Forseti.Examples.GalerkinNS.T3.compiled.outputs.circuit.run
    Gimle.Forseti.Examples.GalerkinNS.T3.compiled.initial
    Gimle.Forseti.Examples.GalerkinNS.T3.enstrophyIndex = 3 :=
  Gimle.Forseti.Examples.GalerkinNS.T3.enstrophy_at_initial

/-- The enstrophy ball `Z ≤ 26`, above the level `f²/(4ν²) = 25`. -/
example : Contract Gimle.Forseti.Examples.GalerkinNS.T3.observed
    Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.T3.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time fun observation =>
      0 ≤ observation Gimle.Forseti.Examples.GalerkinNS.T3.enstrophyIndex ∧
        observation Gimle.Forseti.Examples.GalerkinNS.T3.enstrophyIndex ≤ 26) :=
  Gimle.Forseti.Examples.GalerkinNS.T3.enstrophy_contract

/-- No linear view: the contract is `Nonlinear`'s. -/
example : Gimle.Forseti.Examples.GalerkinNS.T3.compiled.linear.isNone = true := by
  decide +kernel

example : ∃ state, Gimle.Forseti.Examples.GalerkinNS.T3.compiled.Realizes state :=
  Gimle.Forseti.Examples.GalerkinNS.T3.compiled_exists

example : Gimle.Forseti.Examples.GalerkinNS.T3.admitted =
    Initialized Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time (fun _ => True)
      (· = Gimle.Forseti.Examples.GalerkinNS.T3.compiled.initial) := rfl

example (input : Dynamics.Signal (0 + Gimle.Forseti.Examples.GalerkinNS.T3.evolution.states.length))
    (admit : Gimle.Forseti.Examples.GalerkinNS.T3.admitted input)
    (state : Dynamics.Signal Gimle.Forseti.Examples.GalerkinNS.T3.evolution.states.length) :
    Gimle.Forseti.Examples.GalerkinNS.T3.compiled.feedback.Rel
        Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time input state ↔
      Gimle.Forseti.Examples.GalerkinNS.T3.compiled.Realizes state :=
  Gimle.Forseti.Examples.GalerkinNS.T3.feedback_reads input admit state

example (t : ℝ) : t ∈ Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time.domain ↔ 0 ≤ t :=
  Gimle.Forseti.Examples.GalerkinNS.T3.domain_iff t

example : Contract Gimle.Forseti.Examples.GalerkinNS.T3.observed
    Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.T3.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time fun observation =>
      0 ≤ observation Gimle.Forseti.Examples.GalerkinNS.T3.energyIndex ∧
        observation Gimle.Forseti.Examples.GalerkinNS.T3.energyIndex ≤ 13) :=
  Gimle.Forseti.Examples.GalerkinNS.T3.energy_contract

example : Gimle.Forseti.Examples.GalerkinNS.T3.admitted
    (Dynamics.signalAppend Model.noDrivers fun _ =>
      Gimle.Forseti.Examples.GalerkinNS.T3.compiled.initial) :=
  Gimle.Forseti.Examples.GalerkinNS.T3.declared_input_admitted

example : ¬ Holds Gimle.Forseti.Examples.GalerkinNS.T3.observed
    Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.T3.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.T3.evolution.time fun observation =>
      observation Gimle.Forseti.Examples.GalerkinNS.T3.energyIndex ≤ 1) :=
  Gimle.Forseti.Examples.GalerkinNS.T3.refuted

/-- The one triad's flows cancel with the energy weights and with weights one. -/
example : (1 / 1 : ℝ) * (-3 / 20) + (1 / 2 : ℝ) * (2 / 5) + (1 / 5 : ℝ) * (-1 / 4) = 0 ∧
    (-3 / 20 : ℝ) + (2 / 5) + (-1 / 4) = 0 :=
  Gimle.Forseti.Examples.GalerkinNS.T3.triad_0

/-- The trapped level exceeds the laminar energy `f²/(8ν²) = 25/2`, which the
certificate needs strictly. -/
example : Gimle.Forseti.Examples.GalerkinNS.T3.trapping.inner = 25 / 2 := rfl
example : Gimle.Forseti.Examples.GalerkinNS.T3.trapping.bound = 13 := rfl

/-! ### K5 and B2, by their contracts -/

example : Contract Gimle.Forseti.Examples.GalerkinNS.K5.observed
    Gimle.Forseti.Examples.GalerkinNS.K5.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.K5.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.K5.evolution.time fun observation =>
      0 ≤ observation Gimle.Forseti.Examples.GalerkinNS.K5.energyIndex ∧
        observation Gimle.Forseti.Examples.GalerkinNS.K5.energyIndex ≤ 13) :=
  Gimle.Forseti.Examples.GalerkinNS.K5.energy_contract

example : Gimle.Forseti.Examples.GalerkinNS.K5.compiled.initial = ![1, 1, 1, 1, 1] :=
  Gimle.Forseti.Examples.GalerkinNS.K5.initial_eq

example : Contract Gimle.Forseti.Examples.GalerkinNS.B2.observed
    Gimle.Forseti.Examples.GalerkinNS.B2.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.B2.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.B2.evolution.time fun observation =>
      0 ≤ observation Gimle.Forseti.Examples.GalerkinNS.B2.energyIndex ∧
        observation Gimle.Forseti.Examples.GalerkinNS.B2.energyIndex ≤ 313) :=
  Gimle.Forseti.Examples.GalerkinNS.B2.energy_contract

example : Gimle.Forseti.Examples.GalerkinNS.B2.trapping.inner = 625 / 2 := rfl

example : ¬ Holds Gimle.Forseti.Examples.GalerkinNS.B2.observed
    Gimle.Forseti.Examples.GalerkinNS.B2.evolution.time
    Gimle.Forseti.Examples.GalerkinNS.B2.admitted
    (Always Gimle.Forseti.Examples.GalerkinNS.B2.evolution.time fun observation =>
      observation Gimle.Forseti.Examples.GalerkinNS.B2.energyIndex ≤ 1) :=
  Gimle.Forseti.Examples.GalerkinNS.B2.refuted

/-! ### The axiom policy, asserted -/

/--
info: 'Gimle.Forseti.Examples.GalerkinNS.T3.energy_contract'
  depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs (whitespace := lax) in
#print axioms Gimle.Forseti.Examples.GalerkinNS.T3.energy_contract

/--
info: 'Gimle.Forseti.Examples.GalerkinNS.K5.energy_contract'
  depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs (whitespace := lax) in
#print axioms Gimle.Forseti.Examples.GalerkinNS.K5.energy_contract

/--
info: 'Gimle.Forseti.Examples.GalerkinNS.B2.energy_contract'
  depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs (whitespace := lax) in
#print axioms Gimle.Forseti.Examples.GalerkinNS.B2.energy_contract

/--
info: 'Gimle.Forseti.Examples.GalerkinNS.B2.refuted'
  depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs (whitespace := lax) in
#print axioms Gimle.Forseti.Examples.GalerkinNS.B2.refuted

end Gimle.Forseti.Tests.GalerkinNS
