import Gimle.Forseti.BernsteinMatrix

/-! Generated by `tools/aif_metric_pilot.py`.
Untrusted proposals checked by the kernel.
Candidate gzip SHA-256: 96c882a6183ef5cd7e42e517092e50d0a78358a378dd94390241ffa4b92f2c39.
Bin eta ∈ [8,17/2], physical t ∈ [33/5,67/10], s = 10*(t-33/5).
This proves only metric coercivity, not drift, coverage or any trajectory. -/
namespace Gimle.Forseti.Examples.AIFMetricPilot
open Gimle.Forseti.LinearEnergy Gimle.Forseti.BernsteinMatrix

def startMetric : QMatrix 4 :=
  ![![(458704904509 / 250000000000), (-1181863741919 / 1000000000000), (-1053976569287 / 1000000000000), (-10216549899 / 250000000000)],
    ![(-1181863741919 / 1000000000000), (664632736237 / 500000000000), (77603726617 / 500000000000), (-202141690329 / 1000000000000)],
    ![(-1053976569287 / 1000000000000), (77603726617 / 500000000000), (409845935413 / 200000000000), (639782450821 / 1000000000000)],
    ![(-10216549899 / 250000000000), (-202141690329 / 1000000000000), (639782450821 / 1000000000000), (312839069501 / 1000000000000)]]

def endMetric : QMatrix 4 :=
  ![![(1839491356727 / 1000000000000), (-591682381863 / 500000000000), (-1055466473209 / 1000000000000), (-7655228113 / 200000000000)],
    ![(-591682381863 / 500000000000), (332888563863 / 250000000000), (135332370329 / 1000000000000), (-202577313671 / 1000000000000)],
    ![(-1055466473209 / 1000000000000), (135332370329 / 1000000000000), (266381498551 / 125000000000), (648368760647 / 1000000000000)],
    ![(-7655228113 / 200000000000), (-202577313671 / 1000000000000), (648368760647 / 1000000000000), (303518873277 / 1000000000000)]]

def startSlope : QMatrix 4 :=
  ![![(22733825951 / 500000000000), (-14992504533 / 1000000000000), (-1282279223 / 62500000000), (6772950779 / 250000000000)],
    ![(-14992504533 / 1000000000000), (24911170227 / 1000000000000), (-20659394223 / 100000000000), (-4682773821 / 1000000000000)],
    ![(-1282279223 / 62500000000), (-20659394223 / 100000000000), (433664460863 / 500000000000), (96302169749 / 1000000000000)],
    ![(6772950779 / 250000000000), (-4682773821 / 1000000000000), (96302169749 / 1000000000000), (-9927665733 / 100000000000)]]

def endSlope : QMatrix 4 :=
  ![![(47906303219 / 1000000000000), (-596460209 / 40000000000), (-4691967213 / 500000000000), (24595873287 / 1000000000000)],
    ![(-596460209 / 40000000000), (20810963813 / 1000000000000), (-47504322789 / 250000000000), (-101232937 / 25000000000)],
    ![(-4691967213 / 500000000000), (-47504322789 / 250000000000), (190863408037 / 250000000000), (75021795163 / 1000000000000)],
    ![(24595873287 / 1000000000000), (-101232937 / 25000000000), (75021795163 / 1000000000000), (-87111624887 / 1000000000000)]]

-- Recompute the target from the rational Hermite inputs.
def linear : QMatrix 4 := scale (1/10) startSlope
def quadraticTerm : QMatrix 4 := fun i j =>
  3 * (endMetric i j - startMetric i j) -
    (1/10) * (2 * startSlope i j + endSlope i j)
def cubicTerm : QMatrix 4 := fun i j =>
  2 * (startMetric i j - endMetric i j) +
    (1/10) * (startSlope i j + endSlope i j)
def margin : QMatrix 4 :=
  fun i j => startMetric i j - if i = j then 1/50 else 0

def certificate0 : WeightedSquares 4 where
  count := 4
  weight := ![(453704904509 / 250000000000), (979278760200207114138503 / 1814819618036000000000000), (875714801317401500080528476383913977 / 979278760200207114138503000000000000), (21102306575153457010783345933482058203443437909 / 875714801317401500080528476383913977000000000000)]
  vector := ![![(1 / 1), (-1181863741919 / 1814819618036), (-1053976569287 / 1814819618036), (-10216549899 / 453704904509)],
    ![(0 / 1), (1 / 1), (-963983161078015776913329 / 979278760200207114138503), (-415148984804564461238568 / 979278760200207114138503)],
    ![(0 / 1), (0 / 1), (1 / 1), (382767728085363237150767690732722490 / 875714801317401500080528476383913977)],
    ![(0 / 1), (0 / 1), (0 / 1), (1 / 1)]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem valid0 : certificate0.Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm 0 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

def certificate1 : WeightedSquares 4 where
  count := 4
  weight := ![(27245028096491 / 15000000000000), (58895386761500168381939223 / 108980112385964000000000000), (41858027900503609916954101747690822967 / 46012020907422006548390017968750000000), (368602444153168946528096843018957474685741121571003 / 16073482713793386208110375071113276019328000000000000)]
  vector := ![![(1 / 1), (-35470904762103 / 54490056192982), (-15819906773089 / 27245028096491), (-599447092382 / 27245028096491)],
    ![(0 / 1), (1 / 1), (-293277414353236676538069518 / 294476933807500841909696115), (-41469154222821728865872806 / 98158977935833613969898705)],
    ![(0 / 1), (0 / 1), (1 / 1), (1155543924288405845387137273752099245133 / 2678913785632231034685062511852212669888)],
    ![(0 / 1), (0 / 1), (0 / 1), (1 / 1)]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem valid1 : certificate1.Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm 1 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

def certificate2 : WeightedSquares 4 where
  count := 4
  weight := ![(54536834398591 / 30000000000000), (73787260663036562789157371 / 136342085996477500000000000), (2046553752629829073119748198877690225743 / 2213617819891096883674721130000000000000), (4042376062460376359067301333650530159346852674326759 / 184189837736684616580777337898992120316870000000000000)]
  vector := ![![(1 / 1), (-35486031406555 / 54536834398591), (-31654610261844 / 54536834398591), (-1172880090237 / 54536834398591)],
    ![(0 / 1), (1 / 1), (-148585930048561142955105509 / 147574521326073125578314742), (-372837785019041714032759685 / 885447127956438753469888452)],
    ![(0 / 1), (0 / 1), (1 / 1), (1743146849313880361447598619327373162923 / 4093107505259658146239496397755380451486)],
    ![(0 / 1), (0 / 1), (0 / 1), (1 / 1)]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem valid2 : certificate2.Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm 2 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

def certificate3 : WeightedSquares 4 where
  count := 4
  weight := ![(1819491356727 / 1000000000000), (213977749054934464241 / 394854895123046875000), (925170423597553783149412952522592377 / 986009467645138011222528000000000000), (19512709336392721664446313646180021960715749871 / 925170423597553783149412952522592377000000000000)]
  vector := ![![(1 / 1), (-394454921242 / 606497118909), (-1055466473209 / 1819491356727), (-38276140565 / 1819491356727)],
    ![(0 / 1), (1 / 1), (-334255251863563261554517 / 328669822548379337074176), (-137960769109801074686669 / 328669822548379337074176)],
    ![(0 / 1), (0 / 1), (1 / 1), (389304253473674678798134942649307985 / 925170423597553783149412952522592377)],
    ![(0 / 1), (0 / 1), (0 / 1), (1 / 1)]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem valid3 : certificate3.Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm 3 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

def certificates : Fin 4 → Fin 1 → WeightedSquares 4 :=
  fun i _ => ![certificate0, certificate1, certificate2, certificate3] i

theorem valid : ∀ i j, (certificates i j).Represents
    (cubicCoefficients margin linear quadraticTerm cubicTerm i j) := by
  intro i j
  fin_cases i <;> fin_cases j
  · exact valid0
  · exact valid1
  · exact valid2
  · exact valid3

/-- A whole-interval inequality retaining the original Hermite inputs. -/
theorem margin_nonnegative (s : ℝ) (hs : s ∈ Set.Icc (0 : ℝ) 1)
    (x : Fin 4 → ℝ) :
    0 ≤ cubicQuadratic margin linear quadraticTerm cubicTerm s x := by
  rw [← cubic_identity (u := 0)]
  exact tensor_nonnegative certificates valid hs (by norm_num) x

/-- The actual cubic metric controls all four real error coordinates. -/
theorem coercive (s : ℝ) (hs : s ∈ Set.Icc (0 : ℝ) 1) (x : Fin 4 → ℝ) :
    (∑ i, (x i)^2) / 50 ≤
      cubicQuadratic startMetric linear quadraticTerm cubicTerm s x := by
  have h := margin_nonnegative s hs x
  have eq : quadratic margin x =
      quadratic startMetric x - (∑ i, (x i)^2) / 50 := by
    simp [quadratic, realMatrix, margin, Matrix.mulVec, dotProduct,
      Fin.sum_univ_succ]
    ring
  simp only [cubicQuadratic, eq] at h ⊢
  linarith

/-- The same inequality on the candidate's declared physical time interval. -/
theorem coercive_time (t : ℝ) (ht : t ∈ Set.Icc (33/5 : ℝ) (67/10))
    (x : Fin 4 → ℝ) :
    (∑ i, (x i)^2) / 50 ≤ cubicQuadratic startMetric linear quadraticTerm
      cubicTerm (10 * (t - 33/5)) x := by
  apply coercive _ _ x
  constructor <;> linarith [ht.1, ht.2]

#print axioms coercive_time
#print axioms margin_nonnegative
#print axioms coercive
end Gimle.Forseti.Examples.AIFMetricPilot
