import Gimle.Forseti

-- Generated by python -m examples.energy_optimization.
namespace Gimle.Forseti.EnergyOptimizationData

def source : Circuit 2 1 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.compose
        (Circuit.compose
          (Circuit.parallel (leftInput := 1) (leftOutput := 2)
            (Circuit.split)
            (Circuit.split))
          (Circuit.parallel (leftInput := 1) (leftOutput := 1)
            (Circuit.id)
            (Circuit.parallel (leftInput := 2) (leftOutput := 2)
              (Circuit.swap)
              (Circuit.id))))
        (Circuit.parallel (leftInput := 2) (leftOutput := 1)
          (Circuit.add)
          (Circuit.compose
            (Circuit.parallel (leftInput := 1) (leftOutput := 1)
              (Circuit.id)
              (Circuit.scalar (-1 : ℚ)))
            (Circuit.add))))
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.compose (Circuit.split) (Circuit.multiplication))
        (Circuit.compose (Circuit.split) (Circuit.multiplication))))
    (Circuit.add)

def target : Circuit 2 1 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.compose (Circuit.split) (Circuit.multiplication))
        (Circuit.compose (Circuit.split) (Circuit.multiplication)))
      (Circuit.add))
    (Circuit.scalar (2 : ℚ))

namespace Wrong

def source : Circuit 2 1 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.compose
        (Circuit.compose
          (Circuit.parallel (leftInput := 1) (leftOutput := 2)
            (Circuit.split)
            (Circuit.split))
          (Circuit.parallel (leftInput := 1) (leftOutput := 1)
            (Circuit.id)
            (Circuit.parallel (leftInput := 2) (leftOutput := 2)
              (Circuit.swap)
              (Circuit.id))))
        (Circuit.parallel (leftInput := 2) (leftOutput := 1)
          (Circuit.add)
          (Circuit.compose
            (Circuit.parallel (leftInput := 1) (leftOutput := 1)
              (Circuit.id)
              (Circuit.scalar (-1 : ℚ)))
            (Circuit.add))))
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.compose (Circuit.split) (Circuit.multiplication))
        (Circuit.compose (Circuit.split) (Circuit.multiplication))))
    (Circuit.add)

def target : Circuit 2 1 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.compose (Circuit.split) (Circuit.multiplication))
        (Circuit.compose (Circuit.split) (Circuit.multiplication)))
      (Circuit.add))
    (Circuit.scalar (3 : ℚ))

end Wrong

end Gimle.Forseti.EnergyOptimizationData
