import Gimle.Forseti

-- Generated by python -m examples.energy_circuit --lean-data-out.
namespace Gimle.Forseti.EnergyDemoData

def precondition : Predicate 2 where
  holds := fun point => ((((-1 : ℝ)) + ((-1 : ℝ) * (point 1)) ≤ 0) ∧ (((-1 : ℝ)) + ((1 : ℝ) * (point 1)) ≤ 0) ∧ (((-1 : ℝ)) + ((-1 : ℝ) * (point 0)) ≤ 0) ∧ (((-1 : ℝ)) + ((1 : ℝ) * (point 0)) ≤ 0))

def circuit : Circuit 2 1 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.compose
        (Circuit.compose
          (Circuit.parallel (leftInput := 1) (leftOutput := 2)
            (Circuit.split)
            (Circuit.split))
          (Circuit.parallel (leftInput := 1) (leftOutput := 1)
            (Circuit.id)
            (Circuit.parallel (leftInput := 2) (leftOutput := 2)
              (Circuit.swap)
              (Circuit.id))))
        (Circuit.parallel (leftInput := 2) (leftOutput := 1)
          (Circuit.add)
          (Circuit.compose
            (Circuit.parallel (leftInput := 1) (leftOutput := 1)
              (Circuit.id)
              (Circuit.scalar (-1 : ℚ)))
            (Circuit.add))))
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.compose (Circuit.split) (Circuit.multiplication))
        (Circuit.compose (Circuit.split) (Circuit.multiplication))))
    (Circuit.add)

def postcondition : Predicate 1 where
  holds := fun point => ((((-4 : ℝ)) + ((1 : ℝ) * (point 0)) ≤ 0) ∧ (((-1 : ℝ) * (point 0)) ≤ 0))

end Gimle.Forseti.EnergyDemoData
