import Gimle.Forseti

-- Generated by python -m examples.ode_demo.
namespace Gimle.Forseti.OscillatorData

def vectorField : Circuit 2 2 :=
  Circuit.compose
    (Circuit.compose
      (Circuit.parallel (leftInput := 1) (leftOutput := 2)
        (Circuit.split)
        (Circuit.split))
      (Circuit.parallel (leftInput := 1) (leftOutput := 1)
        (Circuit.id)
        (Circuit.parallel (leftInput := 2) (leftOutput := 2) (Circuit.swap) (Circuit.id))))
    (Circuit.parallel (leftInput := 2) (leftOutput := 1)
      (Circuit.parallel (leftInput := 1) (leftOutput := 0)
        (Circuit.terminal)
        (Circuit.id))
      (Circuit.compose
        (Circuit.parallel (leftInput := 1) (leftOutput := 1)
          (Circuit.scalar (-1 : ℚ))
          (Circuit.scalar (-2 : ℚ)))
        (Circuit.add)))

end Gimle.Forseti.OscillatorData
