import Gimle.Forseti.Examples.SuspensionCertificates

/-! Generated by tools/search_suspension.py using exact rational arithmetic.
First accepted candidate: denominator 8, scale 8, after 19 storage candidates.
All targets below are recomputed from the independent typed suspension model.
These are proposals until the ordinary Lean kernel checks their proofs. -/

namespace Gimle.Forseti.Examples.ActiveSuspension.CertificateData

open Gimle.Forseti.LinearEnergy

/-- Discovered common storage matrix, not part of the input specification. -/
def storage : QMatrix 5 :=
  ![![30, (-2), 22, 8, (-1)],
    ![(-2), 51, (-32), (-6), (-4)],
    ![22, (-32), 47, 13, 2],
    ![8, (-6), 13, 6, 1],
    ![(-1), (-4), 2, 1, 2]]

def alpha : ℚ := (1 / 40)
def beta : ℚ := 4096

/-- Exact square decomposition for `storage`. -/
def positive : WeightedSquares 5 where
  count := 5
  weight := ![30, (763 / 15), (9567 / 763), (20051 / 9567), (55083 / 40102)]
  vector := ![![1, (-1 / 15), (11 / 15), (4 / 15), (-1 / 30)],
    ![0, 1, (-458 / 763), (-82 / 763), (-61 / 763)],
    ![0, 0, 1, (2939 / 9567), (223 / 9567)],
    ![0, 0, 0, 1, (7078 / 20051)],
    ![0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem positive_valid : positive.Represents (storage) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `initialMatrix storage`. -/
def initial : WeightedSquares 5 where
  count := 5
  weight := ![70, (1713 / 35), (73 / 3), (3184501 / 41683), (615107617 / 6369002)]
  vector := ![![1, (1 / 35), (-11 / 35), (-4 / 35), (1 / 70)],
    ![0, 1, (2 / 3), (218 / 1713), (139 / 1713)],
    ![0, 0, 1, (-59 / 73), (-13 / 73)],
    ![0, 0, 0, 1, (-203972 / 3184501)],
    ![0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem initial_valid : initial.Represents (initialMatrix storage) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `outputMatrix storage 0`. -/
def output0 : WeightedSquares 5 where
  count := 5
  weight := ![29, (1449 / 29), (1735 / 161), (10903 / 5205), (44909 / 32709)]
  vector := ![![1, (-1 / 29), (22 / 29), (8 / 29), (-1 / 29)],
    ![0, 1, (-302 / 483), (-166 / 1449), (-13 / 161)],
    ![0, 0, 1, (1619 / 5205), (38 / 1735)],
    ![0, 0, 0, 1, (3853 / 10903)],
    ![0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem output0_valid : output0.Represents (outputMatrix storage 0) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `outputMatrix storage 1`. -/
def output1 : WeightedSquares 5 where
  count := 5
  weight := ![30, (763 / 15), (9567 / 763), (20051 / 9567), (14981 / 40102)]
  vector := ![![1, (-1 / 15), (11 / 15), (4 / 15), (-1 / 30)],
    ![0, 1, (-458 / 763), (-82 / 763), (-61 / 763)],
    ![0, 0, 1, (2939 / 9567), (223 / 9567)],
    ![0, 0, 0, 1, (7078 / 20051)],
    ![0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem output1_valid : output1.Represents (outputMatrix storage 1) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `outputMatrix storage 2`. -/
def output2 : WeightedSquares 5 where
  count := 5
  weight := ![29, (1449 / 29), (18037 / 1449), (6611 / 18037), (17599 / 13222)]
  vector := ![![1, (-1 / 29), (21 / 29), (9 / 29), (-1 / 58)],
    ![0, 1, (-878 / 1449), (-194 / 1449), (-131 / 1449)],
    ![0, 0, 1, (4969 / 18037), (181 / 18037)],
    ![0, 0, 0, 1, (288 / 6611)],
    ![0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem output2_valid : output2.Represents (outputMatrix storage 2) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `supplyMatrix storage alpha beta 2`. -/
def slowSupply : WeightedSquares 6 where
  count := 6
  weight := ![(29 / 4), (39003 / 5800), (6249953 / 1560120), (969067251 / 249998120), (201719457317 / 77525380080), (84760873222912 / 201719457317)]
  vector := ![![1, (1 / 145), (-31 / 145), (16 / 145), (-39 / 290), (-128 / 29)],
    ![0, 1, (10502 / 39003), (-10762 / 39003), (4073 / 13001), (140480 / 39003)],
    ![0, 0, 1, (3659501 / 6249953), (-3628383 / 6249953), (-101974240 / 6249953)],
    ![0, 0, 0, 1, (881405438 / 969067251), (6121422560 / 969067251)],
    ![0, 0, 0, 0, 1, (-5900342233600 / 201719457317)],
    ![0, 0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem slowSupply_valid : slowSupply.Represents (supplyMatrix storage alpha beta 2) := by
  unfold WeightedSquares.Represents
  decide +kernel

/-- Exact square decomposition for `supplyMatrix storage alpha beta (5 / 2)`. -/
def fastSupply : WeightedSquares 6 where
  count := 6
  weight := ![(25 / 4), (51943 / 5000), (13397133 / 2077720), (2137288511 / 535885320), (1628252461037 / 170983080880), (5590745636261632 / 1628252461037)]
  vector := ![![1, (-29 / 125), (-21 / 125), (36 / 125), (-19 / 250), (-128 / 25)],
    ![0, 1, (-7218 / 51943), (338 / 51943), (-5051 / 51943), (82880 / 51943)],
    ![0, 0, 1, (3089141 / 13397133), (159169 / 4465711), (-114425440 / 13397133)],
    ![0, 0, 0, 1, (570921768 / 2137288511), (-1175249440 / 2137288511)],
    ![0, 0, 0, 0, 1, (-388366848000 / 1628252461037)],
    ![0, 0, 0, 0, 0, 1]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 4000000 in
theorem fastSupply_valid : fastSupply.Represents (supplyMatrix storage alpha beta (5 / 2)) := by
  unfold WeightedSquares.Represents
  decide +kernel

#print axioms slowSupply_valid
#print axioms fastSupply_valid

end Gimle.Forseti.Examples.ActiveSuspension.CertificateData
